### ISSUE TITLE
"Circle" instead of "Community"

### ISSUE THREAD

**Issue by larmbuster** [redhat-gamedev/arcade.redhat.com#9]
The flavor text right beneath "Red Hat Arcade" near the top of the main page reads "Gaming Circle of Practice" instead of "Gaming Community of Practice".

**Comment by larmbuster** [comment]
![circle_typo20210712](https://user-images.githubusercontent.com/80494138/125348088-c698d080-e329-11eb-9a46-9354b60d2519.png)

**Comment by Jared-Sprague** [comment]
fixed
